//
// Created by johan on 2016-06-22.
//

#ifndef BUBBAROGUEFORT_SCENESWITCHONCOLLISIONCOMPONENT_H
#define BUBBAROGUEFORT_SCENESWITCHONCOLLISIONCOMPONENT_H


class SceneSwitchOnCollisionComponent {

};


#endif //BUBBAROGUEFORT_SCENESWITCHONCOLLISIONCOMPONENT_H
